version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci

  build:
    commands:
      - echo "Creating .env file from environment variables..."
      - export VITE_API_BASE_URL="https://k8s-default-aiccingr-9a828090cc-358415700.ap-northeast-2.elb.amazonaws.com"
      - echo "VITE_API_BASE_URL=$VITE_API_BASE_URL" > .env.production
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://$S3_BUCKET_NAME --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

artifacts:
  base-directory: dist
  files:
    - '**/*'
